[Distribution]
Distribution=arch

[Environment]
SYSTEMD_REPART_MKFS_OPTIONS_BTRFS=-m single -O ^block-group-tree --mixed 

[Build]
ToolsTree=default
WithNetwork=true
SandboxTrees=
        mkosi.sandbox:/
        /etc/pacman.d/mirrorlist:/etc/pacman.d/mirrorlist
        /etc/pacman.d/cachyos-mirrorlist:/etc/pacman.d/cachyos-mirrorlist
        /etc/pacman.d/cachyos-v3-mirrorlist:/etc/pacman.d/cachyos-v3-mirrorlist
        /etc/pacman.d/chaotic-mirrorlist:/etc/pacman.d/chaotic-mirrorlist
        /usr/share/pacman/keyrings:/usr/share/pacman/keyrings
        /etc/pacman.d/gnupg/trustdb.gpg:/etc/pacman.d/gnupg/trustdb.gpg

[Output]
OutputDirectory=mkosi.output
SplitArtifacts=
Format=disk
ImageId=Zena-X
ManifestFormat=json
Output=%i_%v_%a

[Content]
RootPassword=root
UnifiedKernelImages=unsigned
UnifiedKernelImageFormat=%i_%v_%a
KernelCommandLine=
        root=dissect
        mount.usr=dissect
        rw
        audit=0
Bootable=yes
Bootloader=systemd-boot
InitrdProfiles=
KernelInitrdModules=
        default
        erofs
Hostname=zena-x-????-????

Packages=
        acl
        attr
        bash-completion
        btrfs-progs
        ca-certificates
        coreutils
        cpio
        curl
        dbus-broker
        diffutils
        dmidecode
        dms-shell-bin
        dosfstools
        e2fsprogs
        efibootmgr
        erofs-utils
        erofsfuse
        exfatprogs
        file
        findutils
        fwupd
        gdb
        gdisk
        greetd-dms-greeter-git
        grep
        gzip
        jq
        kbd
        kexec-tools
        kmod
        less
        linux-cachyos
        man
        mtools
        nano
        nftables
        niri
        nvme-cli
        opensc
        openssl
        patch
        p11-kit
        pciutils
        pkcs11-provider
        quickshell
        sed
        socat
        strace
        systemd
        tar
        tree
        udev
        unzip
        usbutils
        util-linux
        which
        wireguard-tools
        xxd
        yubikey-manager
        zip
        zstd

RemovePackages=linux

InitrdPackages=
        erofs-utils
        erofsfuse
        btrfs-progs

VolatilePackages=
        systemd
        udev

InitrdVolatilePackages=
        systemd
        udev

# [Validation]
# SecureBoot=yes
# SignExpectedPcr=yes

[Runtime]
RuntimeSize=30G
RAM=4G
CPUs=4
