# [Config]
# MinimumVersion=26~devel

[Distribution]
Distribution=arch

[Config]
ImageVersion=2026.03.25

[Build]
ToolsTree=default
SandboxTrees=mkosi.sandbox:/

[Output]
OutputDirectory=mkosi.output
SplitArtifacts=
Format=disk
ImageId=Zena-X
ManifestFormat=json
Output=%i_%v_%a

[Content]
RootPassword=root
UnifiedKernelImages=unsigned
UnifiedKernelImageFormat=%i_%v_%a
KernelCommandLine=
        root=dissect
        mount.usr=dissect
        rw
        audit=0
Bootable=yes
Bootloader=systemd-boot
InitrdProfiles=
KernelInitrdModules=default
Hostname=zena-x-????-????

PackageManagerTrees=/etc/pacman.d/mirrorlist:/etc/pacman.d/mirrorlist
PackageManagerTrees=/etc/pacman.d/gnupg:/etc/pacman.d/gnupg
PackageManagerTrees=/usr/share/pacman/keyrings:/usr/share/pacman/keyrings
Packages=
        acl
        attr
        bash-completion
        btrfs-progs
        ca-certificates
        coreutils
        cpio
        curl
        dbus-broker
        diffutils
        dmidecode
        dosfstools
        e2fsprogs
        efibootmgr
        erofs-utils
        exfatprogs
        file
        findutils
        fish
        fwupd
        gdb
        gdisk
        grep
        gzip
        jq
        kbd
        kexec-tools
        kmod
        less
        linux-cachyos
        man
        mtools
        nano
        nftables
        nvme-cli
        opensc
        openssl
        patch
        p11-kit
        pciutils
        pkcs11-provider
        sed
        socat
        strace
        systemd
        tar
        tree
        udev
        unzip
        usbutils
        util-linux
        which
        wireguard-tools
        xxd
        yubikey-manager
        zip
        zstd

RemovePackages=linux

VolatilePackages=
        systemd
        udev

InitrdVolatilePackages=
        systemd
        udev

# [Validation]
# SecureBoot=yes
# SignExpectedPcr=yes

[Runtime]
RuntimeSize=30G
RAM=4G
CPUs=4