[Partition]
Type=root
Label=%M-root
Format=btrfs
CopyFiles=/
Subvolumes=
            /var
            /home
            /nix
Minimize=yes
Compression=zstd
SubvolumeMountOptions=/nix:compress=zstd:9,compress-force
MakeDirectories=/nix