[Partition]
Type=root
MountPoint=/
Label=zena-root
Format=btrfs
CopyFiles=/:/
ExcludeFiles=/usr
MakeDirectories=/var /var/cache/dms-greeter /nix
Subvolumes=/etc /var /nix:nodatacow
SizeMinBytes=1G
Compression=zstd
AddValidateFS=no