name: Build Zena-X Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build and upload image
    runs-on: ubuntu-latest
    env: 
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

    container:
      image: cachyos/cachyos-v3:latest
      options: --privileged

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          pacman -Syu --noconfirm \
            jq \
            git \
            cpio \
            mkosi \
            systemd \
            systemd-ukify \
            erofs-utils \
            btrfs-progs \
            dosfstools \
            mtools \
            squashfs-tools

      - name: Prepare repos for mkosi
        run: |
          pacman-key --init
          pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
          pacman-key --lsign-key 3056513887B78AEB

          pacman -U --noconfirm \
            "https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst" \
            "https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst"

      - name: Build Zena-X
        run: |
          mkosi build --output-dir mkosi.output

      - name: Debug EROFS presence
        run: |
          # Find the UKI and check for the erofs driver
          lsinitrd mkosi.output/*.efi | grep erofs || echo "!!! EROFS DRIVER IS MISSING !!!"

      - name: List output
        run: ls -lh mkosi.output

      - name: Upload to Gofile
        run: |
          FILE=$(ls -t mkosi.output/Zena-X_*.raw | head -n1)

          curl --fail \
              --retry 5 \
              --retry-delay 5 \
              --retry-all-errors \
              --connect-timeout 30 \
              --max-time 0 \
              -F "file=@$FILE" \
              https://upload.gofile.io/uploadfile \
              -o response.json
          echo "Response:"
          cat response.json

          echo "Download link:"
          jq -r '.data.downloadPage // .data.file.url.full' response.json || true
